### ISSUE TITLE
Is there a way to deposit? 

### ISSUE THREAD

**Issue by ahdee** [Squirrel-hue/rcbatapi#1]
Hi, thanks for this -- very cool. 
With the old API it was possible to deposit X amount.  Is this possible with the new advance trade? 

thanks.

**Comment by Squirrel-hue** [comment]
Thank you for your kind words. It might be possible, although I may not have implemented it yet.  Let me check to see if that endpoint is enabled by Coinbase.  If it is, I can then try to write the necessary code to permit depositing and withdrawing. I will look into this tomorrow.

**Comment by Squirrel-hue** [comment]
@ahdee I cannot find any support in the documentation for a POST command to deposit using the API.  I think that it would be a great feature, but I can only work with the endpoints provided in the underlying API.

If you have any information about such an endpoint in the Advanced Trading API, please let me know.

**Comment by Squirrel-hue** [comment]
@ahdee I have found a possible way using the "Sign In with CoinBase API."  I have not been able to test this yet, but I think that this should be a valid approach.
 
[R Sign In with CoinBase API rsiwcbapi](https://github.com/Squirrel-hue/rsiwcbapi)

I created a new repository in order to avoid affecting anything that is currently working in the other repository.  I may combine the the code to the rcbatapi repository at some future date.

Let me know if this helps.

**Comment by ahdee** [comment]
@Squirrel-hue cool thank you and thanks for looking into this. I will test this out when  I get a chance; its one of the most important part of an automated system and I'm not sure why coinbase is not making this a standard thing.

**Comment by Squirrel-hue** [comment]
@ahdee  Thank you for getting back to me; I will also test it out more.  Once it is working, I may try to implement more functions to streamline the process.

**Comment by Squirrel-hue** [comment]
@ahdee  I was able to deposit following the procedure in the README file of the following project:

[R Sign In with CoinBase API rsiwcbapi](https://github.com/Squirrel-hue/rsiwcbapi)

I am closing this issue with this response, but please let me know if you have any further questions.  Happy automated trading!
